feat: implement filters for single district
Project-Lavinia/Lavinia-client pull request #255
Opened 2020-08-28 09:34 UTC by Log234

# Description
Adds filters to the Single District view.

## Issues closed
Closes #252

2020-09-03 15:02 UTC, simendag commented
I suggest we put this PR on hold until we can resolve #254 

We might even fix it in this PR.

2020-10-18 13:58 UTC, simendag requested changes

2020-10-18 13:58 UTC, simendag commented on src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
> +import { norwegian, caseInsensitiveFilterMethod, selectFilterWithOptions, thresholdOptions, thresholdFilterMethod, eqOrNeqZeroOptions, allGreaterThanEqualsMethod, positiveOrNegativeFilterMethod } fro
This really should be on more than one line.

2026-07-16 08:48 UTC, Log234 commented
This PR is being superseded by #353

2026-07-16 08:48 UTC, closed without merging