Add dynamic content to tooltipinfo in presentation selection
Project-Lavinia/Lavinia-client pull request #260
Opened 2020-09-01 11:18 UTC by oysor

## Issues closed
#213

2020-09-01 11:20 UTC, Log234 commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817&bid=19980878)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +                };;
Codacy found an issue: [Unnecessary semicolon.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case 'SEAT_DISTRIBUTION': {
Codacy found an issue: [Strings must use doublequote.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case 'TABLE_SINGLE_COUNTY': {
Codacy found an issue: [Strings must use doublequote.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case 'TABLE_LEVELLING_SEATS_OVERVIEW': {
Codacy found an issue: [Strings must use doublequote.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case 'TABLE_REMAINDER_QUOTIENTS': {
Codacy found an issue: [Strings must use doublequote.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case 'TABLE_ELECTION_OVERVIEW': {
Codacy found an issue: [Strings must use doublequote.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-01 11:20 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case 'TABLE_DISTRICT_OVERVIEW': {
Codacy found an issue: [Strings must use doublequote.](https://app.codacy.com/gh/Project-Lavinia/Lavinia-client/pullRequest?prid=6103817)

2020-09-02 11:15 UTC, Log234 requested changes
Two minor tweaks, but otherwise a great PR!

2020-09-02 11:15 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +                    text: "Her kan du se valgresultatet på landsbasis. Trykk på meg for mer informasjon!",
I would suggest we remove the "Trykk på meg for mer informasjon!" as this is already mentioned in the tutorial.

2020-09-02 11:15 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +                return {
The default case should use the checkExhaustively function to ensure we never reach the default case.

2020-09-02 17:02 UTC, Log234 requested changes
There are two texts that appear to have been swapped.

2020-09-02 17:02 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case PresentationType.RemainderQuotients: {
You seem to have swapped the texts for RemainderQuotients and SeatDistribution.

2020-09-02 17:02 UTC, Log234 commented on src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
> +            case PresentationType.SeatDistribution: {
You seem to have swapped the texts for SeatDistribution and RemainderQuotients.

2020-09-02 18:42 UTC, oysor commented
The tooltip text could probably be better.

2020-09-04 09:41 UTC, Log234 commented
@oysor Would you mind adding a tooltip for the new table before we merge?

2020-09-04 10:39 UTC, Log234 approved these changes
Looks good to me!

2020-09-04 11:20 UTC, merged