fix: Add missing parties to each district
Project-Lavinia/Lavinia-client pull request #304
Opened 2022-03-06 10:04 UTC by Log234

Currently, the table District distribution of seats may show incorrect data, due to not every party receiving votes in every district. The consequence of this is that the values to the right of the missing party is shifted one to the left for each missing party. To fix this, this PR simply adds missing parties to each district with 0 votes, which ensures that the values end up in the correct columns.

The PR also corrects some table sizes and pagination to ensure all districts can be show, even when there are more than 19 districts in an election (see 1945 and 1949).

2026-07-07 06:26 UTC, simendag requested changes
We need to understand why Cypress tests are failing and whether that's OK.

2026-07-12 09:31 UTC, simendag commented
Do we rebase this on master and see that things still work?

2026-07-12 14:39 UTC, simendag commented on src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
> +                    defaultPageSize={20}
I really don't like this magic number. Is it meant to be computed? Is it meant to be a default for UI reasons? Could we make it a reasonably named const?

2026-07-12 15:00 UTC, Log234 commented on src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
> +                    defaultPageSize={20}
I agree, I think I'll abandon this PR as the main issue it is resolving appears to already have been fixed in #316.

2026-07-12 15:03 UTC, Log234 commented
Closing PR as the main problem the PR is resolving was implemented in #316.

2026-07-12 15:03 UTC, closed without merging